### ISSUE TITLE
Status: ERROR 7 while retrieving SMS

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#5]
Now the SMS button is active when you set the following option in the `ussd-gui` config file:

`source=internal`

But when you click the button, you get `Status: ERROR 7` .

**Comment by mhogomchungu** [comment]
The internal backend currently uses libgammu internally for retrieval of sms messages.

This means you need to have functional libgammu for it to work.

Install "wammu",a libgammu front end and then go to menu->phone->connect and then menu->retrieve->messages. If wammu can retrieve your messages,then ussd-gui using both backends will be able to do the same.

**Comment by morfikov** [comment]
I have `wammu` and it can do it. Only `ussd-gui` stopped doing so.

I just checked using `libgammu` setting, and here it works just fine, so only `internal` is affected.

**Comment by morfikov** [comment]
BTW, are you planning to implement sending/removing/receiving SMS via AT commands?

**Comment by mhogomchungu** [comment]
Can you try again? I can access sms messages just fine using the internal backend. Maybe you tried the internal backend while your modem was in a bad state. It is the same code path and hence access sms using libgammu backend and internal backend should give the same result.

Those features are in my todo list but i am in no hurry to implement them. I wanted to be able to send USSD codes because i was tired of booting to windows just to do so,then i implemented reading sms messages because the phone company responds to some inquires by sending text messages and i use wammu to delete text messages when the modem becomes full.

Necessity has brought me here,more features from here onwards are a nice to have have but not very important to me.

**Comment by morfikov** [comment]
I tried the newest commit. It is all the same. I get the error in question only when I press the SMS button, but I am able to send/receive USSD codes. So clearly something is wrong with it.

**Comment by mhogomchungu** [comment]
Try again as i made a few changes that i hope will solve the problem.

**Comment by morfikov** [comment]
This has been fixed.
