### ISSUE TITLE
Resizable windows

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#8]
1 Is there a way to make the `ussd-gui` windows resizable?
2 When you add multiple USSD codes to favorites, at some point the horizontal scrollbar appears. It looks like it's because of the vertical scrollbar but the columns have fixed width. You can change the width but after closing the window, the values are restored. Would be possible to fix that, so the horizontal scrollbar disappeared?

**Comment by mhogomchungu** [comment]
The size of the favorite window is now configurable and new dimensions survives restart.

**Comment by morfikov** [comment]
I've just tested this, and it looks like that the horizontal scrollbar in favorites is gone forever. What about the main window? Will it be resizable too?

**Comment by mhogomchungu** [comment]
The main window is now also resizable.

The resizable window looks weird to me and hence i have added a compile time option to set the window either as fixed or as resizable. I will be using the fixed version personally and you will get the dynamic version simply by compiling the project since its the default.

**Comment by morfikov** [comment]
What's wrong with the window? It looks just fine to me:

![2016-05-01-16 55 22_ussd-gui](https://cloud.githubusercontent.com/assets/3797768/14942449/c307c7a4-0fbd-11e6-86fe-c522c50eb6a9.png)

**Comment by mhogomchungu** [comment]
Maybe its because you did not design it :-)

To start with,the distance of the "convert" button to the left edge is not the same as the distance of the "quit" button to the right edge.

I like things to be centered and the lower button line is not centered and that is something i did not expect to happen when i push the commit,things looked fine on my end.

**Comment by mhogomchungu** [comment]
can you update again and post a picture of the new GUI.

I did a hack earlier and it looked good on my end but not on yours and i hope i have done it the right way this time.

**Comment by morfikov** [comment]
![2016-05-01-19 17 58_ussd-gui](https://cloud.githubusercontent.com/assets/3797768/14943138/86aed072-0fd1-11e6-8793-863bc3483716.png)

**Comment by mhogomchungu** [comment]
That looks much better :-)
